name: 'release'

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - { target: 'x86_64-apple-darwin'       , os: 'macos-latest'  }
          - { target: 'x86_64-unknown-linux-gnu'  , os: 'ubuntu-latest' }
          - { target: 'x86_64-unknown-linux-musl' , os: 'ubuntu-latest' }

    runs-on: '${{ matrix.os }}'

    steps:
      - uses: 'actions/checkout@v2'

      - uses: 'actions-rs/toolchain@v1'
        with:
          toolchain: 'stable'

      - uses: 'actions-rs/cargo@v1'
        with:
          command: 'build'
          args: '--all-features --release --target ${{ matrix.target }} --verbose'
          use-cross: true

      - uses: 'svenstaro/upload-release-action@2.1.1'
        with:
          file: 'target/${{ matrix.target }}/release/xansi'
          tag: '${{ github.ref }}'
          asset_name: 'xansi-${{ matrix.target }}'
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
